site:
  title: Docs Site
  start_page: adocs::index.adoc
content:
  sources:
    - url: .
      branches: master

asciidoc:
  attributes:
    imagesdir: images

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true

output:
  dir: build/site